config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  root "products#index"
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/product.rb
class Product < ApplicationRecord
    has_rich_text :description
    has_one_attached :featured_image
    validates :name, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully edited." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity, alert: "Failed to update the product. Please check the errors below." }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :featured_image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background: #252525;">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand text-light" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Left-side Navigation -->
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "New Product", new_product_path, class: "nav-link text-light" %>
        </li>
      </ul>

      <!-- Account Section -->
      <div class="d-flex align-items-center">
        <div class="me-3 text-light">
          <% if authenticated? %>
            <span><%= button_to "Đăng xuất", session_path, method: :delete, class: "btn btn-outline-light btn-sm" %></span>
          <% else %>
            <span><%= link_to "Đăng nhập", new_session_path, class: "btn btn-outline-light btn-sm" %></span>
          <% end %>
        </div>

        <!-- Search Form -->
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Storecasi" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      
    <%= render "home/header" %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<% if product.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>
<%= form_with(model: @product, local: true) do |form| %>
    <div>
        <%= form.label :name %> <br>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.rich_text_area :description %>
    </div>
    <div>
        <%= form.label :featured_image, style: "display: block" %>
        <%= form.file_field :featured_image, accept: "image/*" %>
    </div>
    <div class="mt-1">
        <%= form.submit class:'btn btn-secondary' %>
    </div>
    
<% end %>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>
<h1>Edit</h1>
<%= render "form", product: @product %>
<br>
<div>
  <%= link_to "Show", @product, class:"btn btn-secondary" %> 
  <%= link_to "Back", products_path, class:"btn btn-dark" %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>
<% if authenticated? %>

<% else %>
<%= link_to "New Product", new_product_path, class:"btn btn-outline-primary" %>
<% end %>
<table style="width:300px;" class="table table-striped table-bordered table-hover mt-1">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <%= link_to product.name, product, class:"link-underline link-underline-opacity-0 text-dark" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render "form", product: @product %>

<div class="mt-1">
    <%= link_to "Back", root_path, class:"btn btn-dark" %>
</div>

app/views/products/show.html.erb
<div class="mb-2">
  <% cache @product do %>
    <h1><%= @product.name %></h1>
    <%= @product.description %>
    <%= image_tag @product.featured_image, style: "width: 200px; height: 200px; object-fit: cover;", alt: @product.name if @product.featured_image.attached? %>
  <% end %>
</div>
<div style="display:flex; justify-content: space-between; width:200px">
  <% if authenticated? %>
  <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-secondary" %>
  <%= button_to "Delete", @product, data: { turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger delete-button" %>
  <% end %>
  <%= link_to 'Back', products_path, class:"btn btn-dark" %>
</div>